# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
- pdf
