# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

requirements_file: docs/requirements.txt

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
- pdf
