# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
- pdf
